-- Source: https://isaac.huijiwiki.com/wiki/成就 (Data:Achievement.tabx)
-- Generated by tools/generate_achievement_catalog.mjs; edit the source data or generator instead.
local function reward(kind,id) return {kind=kind,id=id} end
local function observe(kind,value) return {kind=kind,values={value}} end
local function a(number,zhName,enName,zhDetail,enDetail,unlockReward,observation)
  return {
    id="achievement_"..number, achievementId=number, category="achievement",
    reward=unlockReward, observation=observation,
    zh={name=string.format("#%03d %s",number,zhName),detail=zhDetail},
    en={name=string.format("#%03d %s",number,enName),detail=enDetail}
  }
end

return {
  a(601,"大箱子","Mega Chest","用堕化以撒获得超级撒但通关标记。","Defeat Mega Satan as Tainted Isaac"),
  a(602,"红桃Q","Queen of Hearts","用堕化抹大拉获得超级撒但通关标记。","Defeat Mega Satan as Tainted Magdalene",reward("card",79)),
  a(603,"金胶囊","Gold Pill","用堕化该隐获得超级撒但通关标记。","Defeat Mega Satan as Tainted Cain"),
  a(604,"黑福袋","Black Sack","用堕化犹大获得超级撒但通关标记。","Defeat Mega Satan as Tainted Judas"),
  a(605,"友好大便","Charming Poop","用堕化???获得超级撒但通关标记。","Defeat Mega Satan as Tainted ???"),
  a(606,"大胶囊","Horse Pill","用堕化夏娃获得超级撒但通关标记。","Defeat Mega Satan as Tainted Eve"),
  a(607,"夹娃娃机","Crane Game","用堕化参孙获得超级撒但通关标记。","Defeat Mega Satan as Tainted Samson"),
  a(608,"地狱抽奖","Hell Game","用堕化阿撒泻勒获得超级撒但通关标记。","Defeat Mega Satan as Tainted Azazel"),
  a(609,"木箱子","Wooden Chest","用堕化拉撒路获得超级撒但通关标记。","Defeat Mega Satan as Tainted Lazarus"),
  a(610,"万用牌","Wild Card","用堕化伊甸获得超级撒但通关标记。","Defeat Mega Satan as Tainted Eden",reward("card",80)),
  a(611,"闹鬼箱子","Haunted Chest","用堕化游魂获得超级撒但通关标记。","Defeat Mega Satan as Tainted Lost"),
  a(612,"愚人金","Fool's Gold","用堕化莉莉丝获得超级撒但通关标记。","Defeat Mega Satan as Tainted Lilith"),
  a(613,"金硬币","Golden Penny","用堕化店主获得超级撒但通关标记。","Defeat Mega Satan as Tainted Keeper"),
  a(614,"腐烂乞丐","Rotten Beggar","用堕化亚玻伦获得超级撒但通关标记。","Defeat Mega Satan as Tainted Apollyon"),
  a(615,"金电池","Golden Battery","用堕化遗骸获得超级撒但通关标记。","Defeat Mega Satan as Tainted Forgotten"),
  a(616,"忏悔室","Confessional","用堕化伯大尼获得超级撒但通关标记。","Defeat Mega Satan as Tainted Bethany"),
  a(617,"金饰品","Golden Trinket","用堕化雅各获得超级撒但通关标记。","Defeat Mega Satan as Tainted Jacob"),
  a(618,"以撒的魂石","Soul of Isaac","用堕化以撒获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Isaac",reward("card",81)),
  a(619,"抹大拉的魂石","Soul of Magdalene","用堕化抹大拉获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Magdalene",reward("card",82)),
  a(620,"该隐的魂石","Soul of Cain","用堕化该隐获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Cain",reward("card",83)),
  a(621,"犹大的魂石","Soul of Judas","用堕化犹大获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Judas",reward("card",84)),
  a(622,"???的魂石","Soul of ???","用堕化???获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted ???",reward("card",85)),
  a(623,"夏娃的魂石","Soul of Eve","用堕化夏娃获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Eve",reward("card",86)),
  a(624,"参孙的魂石","Soul of Samson","用堕化参孙获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Samson",reward("card",87)),
  a(625,"阿撒泻勒的魂石","Soul of Azazel","用堕化阿撒泻勒获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Azazel",reward("card",88)),
  a(626,"拉撒路的魂石","Soul of Lazarus","用堕化拉撒路获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Lazarus",reward("card",89)),
  a(627,"伊甸的魂石","Soul of Eden","用堕化伊甸获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Eden",reward("card",90)),
  a(628,"游魂的魂石","Soul of the Lost","用堕化游魂获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Lost",reward("card",91)),
  a(629,"莉莉丝的魂石","Soul of Lilith","用堕化莉莉丝获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Lilith",reward("card",92)),
  a(630,"店主的魂石","Soul of the Keeper","用堕化店主获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Keeper",reward("card",93)),
  a(631,"亚玻伦的魂石","Soul of Apollyon","用堕化亚玻伦获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Apollyon",reward("card",94)),
  a(632,"遗骸的魂石","Soul of the Forgotten","用堕化遗骸获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Forgotten",reward("card",95)),
  a(633,"伯大尼的魂石","Soul of Bethany","用堕化伯大尼获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Bethany",reward("card",96)),
  a(634,"雅各与以扫的魂石","Soul of Jacob and Esau","用堕化雅各获得头目车轮战和死寂通关标记。","Defeat Hush and Boss Rush as Tainted Jacob",reward("card",97)),
  a(635,"奇怪的门","A Strange Door","击败母亲1次。","Defeat Mother"),
  a(636,"死亡证明","Death Certificate","用所有人物获得所有困难通关标记。","Earn all Hard mode Completion Marks for all characters, including tainted ones",reward("collectible",628)),
  a(637,"弑神大神","Dead God","解锁所有其他成就并收集所有物品。","Unlock all the other achievements and collect every item in the game"),
  a(638,"游玩联机模式","Play Online","进行一次在线联机游戏","Play an online match once"),
  a(639,"通关联机模式","Win Online","赢得一次在线联机游戏","Win an online match once"),
  a(640,"通关联机每日挑战","Win Online Daily","赢得一次在线每日挑战","Win an online Daily Run once"),
  a(641,"读它！","Read Up!","击败妈妈","Defeat Mom"),
}
