import fs from "node:fs";
import path from "node:path";

const [sourcePath] = process.argv.slice(2);
if (!sourcePath) throw new Error("Usage: node tools/generate_achievement_catalog.mjs <achievements.json>");

const root = path.resolve(import.meta.dirname, "..");
const entries = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const quote = (value) => JSON.stringify(value ?? "");

const characterObservations = new Map([
  [199, 13], [251, 14], [340, 15], [390, 16], [404, 18], [405, 19],
  [474, 21], [475, 22], [476, 23], [477, 24], [478, 25], [479, 26],
  [480, 27], [481, 28], [482, 29], [483, 30], [484, 31], [485, 32],
  [486, 33], [487, 34], [488, 35], [489, 36], [490, 37]
]);
const taintedUnlockRoutes = new Set(Array.from({ length: 17 }, (_, index) => 474 + index));

function rewardFor(entry) {
  const match = (entry.rewardWikiUrl || "").match(/\/(C|T|K)(\d+)$/);
  if (!match) return null;
  return `reward("${({ C: "collectible", T: "trinket", K: "card" })[match[1]]}",${Number(match[2])})`;
}

function renderEntry(entry) {
  const fields = [
    String(Number(entry.id)), quote(entry.nameZh), quote(entry.nameEn),
    quote(entry.unlockCondition), quote(entry.unlockConditionEn)
  ];
  const reward = rewardFor(entry);
  const playerType = characterObservations.get(Number(entry.id));
  const routeKind = taintedUnlockRoutes.has(Number(entry.id)) ? "tainted_unlock" : null;
  if (reward || playerType || routeKind) fields.push(reward || "nil");
  if (playerType || routeKind) fields.push(playerType ? `observe("player",${playerType})` : "nil");
  if (routeKind) fields.push(quote(routeKind));
  return `  a(${fields.join(",")}),`;
}

const ranges = [[101, 200], [201, 300], [301, 400], [401, 500], [501, 600], [601, 641]];
for (const [start, end] of ranges) {
  const rows = entries.filter(({ id }) => Number(id) >= start && Number(id) <= end);
  if (rows.length !== end - start + 1) throw new Error(`Incomplete range ${start}-${end}`);
  const output = [
    "-- Source: https://isaac.huijiwiki.com/wiki/成就 (Data:Achievement.tabx)",
    "-- Generated by tools/generate_achievement_catalog.mjs; edit the source data or generator instead.",
    "local function reward(kind,id) return {kind=kind,id=id} end",
    "local function observe(kind,value) return {kind=kind,values={value}} end",
    "local function a(number,zhName,enName,zhDetail,enDetail,unlockReward,observation,routeKind)",
    "  return {",
    "    id=\"achievement_\"..number, achievementId=number, category=\"achievement\",",
    "    reward=unlockReward, observation=observation, routeKind=routeKind,",
    "    zh={name=string.format(\"#%03d %s\",number,zhName),detail=zhDetail},",
    "    en={name=string.format(\"#%03d %s\",number,enName),detail=enDetail}",
    "  }",
    "end",
    "",
    "return {",
    ...rows.map(renderEntry),
    "}",
    ""
  ].join("\n");
  fs.writeFileSync(path.join(root, "scripts", "data", `achievements_${start}_${end}.lua`), output, "utf8");
}
